version: '3.1'
services:
  db:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
      # MYSQL_DATABASE: database
    # ports:
    #   - "3306:3306"
    # volumes:
    #   - ./mysql/databases:/var/lib/mysql
    #   - ./log/mysql:/var/log/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
